import React from 'react'

export default function TosPage() {
  return (
    <div className="w-full mx-auto px-8 py-4">
      <h1 className="text-2xl font-bold mb-4">Memepump.gg Terms of Service</h1>
      <p className="text-sm text-gray-600 mb-4">Last updated: June 4, 2025</p>

      <p className="mb-4">
Welcome to Memepump.gg! These Terms of Service, together with any referenced documents and additional terms (collectively, the "Terms of Service"), are entered into by Memepump.gg (collectively, "Memepump", "we", "us", and "our") and you, or the company or other legal entity you represent ("you" or "your").
      </p>

      <p className="mb-4">
        By accessing or using the Services in any way, you confirm that (1) you have read, understood, and agree to be bound by these Terms of Service; (2) you are of legal age to form a binding contract with us; and (3) you have the authority to enter into these Terms of Service.
      </p>

      <p className="font-bold mb-4">
        IF YOU DO NOT AGREE TO BE BOUND BY THE TERMS OF SERVICE, YOU MAY NOT ACCESS OR USE THE SERVICES.
      </p>

      <p className="mb-4">
Use of and participation in certain Services may be subject to additional terms, which will be listed in the Terms of Service or presented to you for acceptance when you register for such additional Services. If the Terms of Service are inconsistent with the Additional Terms, the Additional Terms will prevail for those Services.
      </p>

      <p className="mb-4">
The Services allow users to discover, track, and interact with data generated by compatible third-party blockchain applications.
      </p>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">IMPORTANT DISCLAIMER:</h2>
        <p className="mb-3">
BY USING THE SERVICES PROVIDED BY MEMEPUMP, YOU SHOULD NOT EXPECT TO EARN PROFITS OR GENERATE RETURNS FROM TRADING, RECEIVING, OR OWNING DIGITAL ASSETS LISTED ON MEMEPUMP. YOU SHOULD ALSO NOT EXPECT ANYONE TO MAKE EFFORTS OR PROVIDE SUPPORT TO ACHIEVE PROFITS OR RETURNS FROM THE DIGITAL ASSETS YOU HOLD OR TRADE.
        </p>
        <p className="mb-3">
THE DIGITAL ASSETS LISTED ON MEMEPUMP HAVE NO PRACTICAL USE OR FUNCTION, AS THEY ARE FOR ENTERTAINMENT PURPOSES ONLY. PLEASE NOTE THAT YOU MAY LOSE ALL THE MONEY YOU USE TO PURCHASE THESE DIGITAL ASSETS.
        </p>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">LEGAL DISCLAIMER:</h2>
        <p className="mb-3">
MEMEPUMP IS NOT A BROKER, FINANCIAL INSTITUTION, OR INTERMEDIARY AND IS NOT YOUR AGENT, ADVISOR, OR CUSTODIAN. MEMEPUMP CANNOT INITIATE TRANSFERS OF ANY CRYPTOCURRENCY OR DIGITAL ASSET OR ACCESS YOUR DIGITAL ASSETS IN YOUR OWN WEB3 WALLET.
        </p>
        <p className="mb-3">
MEMEPUMP HAS NO RELATIONSHIP OR FIDUCIARY DUTY TO YOU REGARDING ANY DECISION OR ACTIVITY YOU UNDERTAKE IN CONNECTION WITH YOUR USE OF THE SERVICES.
        </p>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">1. DEFINITIONS</h2>
        <dl className="space-y-2">
          <div>
            <dt className="font-semibold">1.1 "Adapter"</dt>
            <dd>means a software tool that enables and facilitates the interoperability of a specific DeFi project with the Services.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.2 "Additional Referral Terms"</dt>
            <dd>means any additional tools published in a referral invitation or linked to any specific referral program or promotional code.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.3 "Agreement"</dt>
            <dd>means these Terms of Service and any Additional Terms applicable to your use of the Services.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.4 "Arbitration Agreement"</dt>
            <dd>means the dispute resolution mechanism in Section 16.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.5 "Brand"</dt>
            <dd>means, for any Adapter, the trademark, logo, or other identifying mark of the DeFi project or other third-party entity whose interoperability is facilitated by that Adapter.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.6 "Connected Content"</dt>
            <dd>means any Content or personal financial data you have provided and stored in your Wallet.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.7 "Content"</dt>
            <dd>means any information, data, text, software, music, sound, images, graphics, video, messages, tags, and/or other materials.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.8 "Digital Asset"</dt>
            <dd>means any cryptocurrency, crypto asset, blockchain-based token, or other digital asset supported by the Services.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.9 "Ecosystem Partner"</dt>
            <dd>means supported DeFi applications and projects.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.10 "Feedback"</dt>
            <dd>means any ideas, suggestions, materials, and/or proposals you submit to MEMEPUMP via Discord or through the Services.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.11 "Friend"</dt>
            <dd>means an individual known to the referrer.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.12 "Incentive"</dt>
            <dd>means any benefit a referrer may receive for participating in the Referral Program.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.13 "Provide"</dt>
            <dd>means to upload, post, email, transmit, or otherwise make available through the Services.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.14 "OSS" or "Open Source Software"</dt>
            <dd>means any software or component thereof that is subject to an "open source" or "free software" license.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.15 "Referral Link"</dt>
            <dd>means a personal link or code used by a referrer to refer friends to the Services through the Referral Program.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.16 "Referral Program"</dt>
            <dd>means the referral rewards program provided by MEMEPUMP under the terms of Section 18 of this Agreement.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.17 "Referrer"</dt>
            <dd>means a Registered User participating in the Referral Program.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.18 "Registered User"</dt>
            <dd>means a user with a valid Third-Party Account, including but not limited to a Wallet, through which the user has connected to the Services.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.19 "Services"</dt>
            <dd>means any products and services provided by MEMEPUMP.GG</dd>
          </div>
          <div>
            <dt className="font-semibold">1.20 "Additional Terms"</dt>
            <dd>means any terms or policies applicable to any product or service provided by MEMEPUMP not mentioned in these Terms of Service.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.21 "Telegram Bot"</dt>
            <dd>means an automated program running on the Telegram messaging platform, capable of interacting with users via messages and commands to perform various tasks.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.22 "Terms of Service"</dt>
            <dd>means this MEMEPUMP Terms of Service Agreement governing your access to and use of the Services.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.23 "Third-Party Account"</dt>
            <dd>means a valid account on a third-party service provider or social network supported by the Services, such as Facebook, Twitter, or GitHub, or a valid third-party Wallet compatible with the Services.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.24 "Third-Party Service"</dt>
            <dd>means any third-party website, application, and advertisement that may be accessed or connected to the Services but is not provided by MEMEPUMP.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.25 "User Content"</dt>
            <dd>means any Content Provided by a Registered User on or through the Services.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.26 "Wallet"</dt>
            <dd>means a software-based system for securely storing cryptocurrency, crypto assets, and related payment information.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.27 "Website"</dt>
            <dd>means https://www.memepump.gg</dd>
          </div>
          <div>
            <dt className="font-semibold">1.28 "You"</dt>
            <dd>means the individual or entity, as applicable, using or accessing the Services, or identified as a user when you register on the Services.</dd>
          </div>
          <div>
            <dt className="font-semibold">1.29 "MEMEPUMP", "we", "us", "our"</dt>
            <dd>means memepump.gg</dd>
          </div>
          <div>
            <dt className="font-semibold">1.30 "MEMEPUMP Parties"</dt>
            <dd>means MEMEPUMP, its parent company, subsidiaries, affiliates, officers, employees, agents, partners, suppliers, and licensors.</dd>
          </div>
        </dl>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">2. USE OF SERVICES</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">2.1 License to Use the Services</h3>
            <p>The Services are protected by copyright laws worldwide. Subject to the Agreement, MEMEPUMP grants you a limited license to copy portions of the Services solely for your personal or internal business use of the Services.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">2.2 Updates</h3>
            <p>You understand that the Services are evolving. You acknowledge and agree that MEMEPUMP may update the Services without notice to you.</p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">3. TELEGRAM BOT AND SERVICES</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">3.1 General Services</h3>
            <p>MEMEPUMP is a sophisticated tool designed for digital asset traders, providing comprehensive capabilities to scan and analyze blockchain data. MEMEPUMP converts complex on-chain data into clear, actionable insights and helps users make informed decisions quickly and wisely. By monitoring the effectiveness of various activities related to smart contracts and wallet addresses, MEMEPUMP helps users maintain close oversight of their digital assets and "smart money".</p>
            <p className="mt-2">To avoid confusion, the information presented on MEMEPUMP is based on the activities monitored by the platform; no information is created or altered by MEMEPUMP. Additionally, MEMEPUMP will not be responsible for the accuracy, reliability, or completeness of any information, nor for any losses or damages arising from its use.</p>
            <p className="mt-2">Users are encouraged to conduct their own due diligence and consult with experts before making any financial decisions based on detailed information provided by MEMEPUMP. By using this service, users acknowledge and agree to these terms, including the limitations of liability set forth herein.</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">3.2 Copy Trading Function</h3>
            <p>You can use MEMEPUMP's dashboard to determine the "smart money" addresses, which allows for automatic copying of transactions with a single click. This feature simplifies the process of copying successful transactions executed by experienced investors, allowing you to benefit from their expertise.</p>
            <p className="mt-2">You acknowledge and agree that while the Telegram bot facilitates copying of transactions, it operates exclusively based on the parameters you set. You must clearly select which address to follow and set the criteria for automatic copying. All transactions start based on your instructions and preferences.</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">3.3 Account Management</h3>
            <p>The Telegram bot allows you to manage your blockchain wallets seamlessly through its interface, including creating and managing wallet addresses and access keys. You can perform various activities, such as checking balances and executing transactions, while maintaining control over your private keys.</p>
            <p className="mt-2">The Telegram bot functions as an interface that allows you to interact with your wallet created by MEMEPUMP. When you transfer funds to this wallet, you retain control over your private keys and your assets. The bot facilitates automatic transactions on your behalf.</p>
            <p className="mt-2">MEMEPUMP will monitor market conditions and notify you when certain criteria are met. However, the execution of transactions remains under your control, ensuring that you have the final say in all transaction activities. You are fully responsible for securing your login information and private keys, and you agree to follow the best practices for protecting your information.</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">3.4 Integration and Data Analysis</h3>
            <p>The Telegram bot allows you to access data from various decentralized applications, including decentralized exchanges ("DApps"). This feature provides you with the necessary information to make informed trading decisions based on real-time data.</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">3.5 Cross-Chain Trading</h3>
            <p>You can start cross-chain trading of Digital Assets directly through the Telegram bot interface, using integrated technology from third-party DApps. MEMEPUMP does not verify or assume responsibility for any DApp or third-party service accessed through the Telegram bot. We recommend that you review the terms, conditions, and security policies of any third-party service before using them.</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">3.6 Broadcasting Transactions</h3>
            <p>The Telegram bot may allow you to view addresses and related information in the digital asset network and broadcast transactions using various DApps or data sources. This feature allows for efficient transaction execution based on current network data.</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">3.7 Adjustable Transaction Parameters</h3>
            <p>You have full control over the trading strategy of your own. You can set and adjust transaction parameters to ensure that all activities of the Telegram bot are consistent with your specific trading preferences.</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">3.8 Disclaimer and Limitation of Liability</h3>
            <p>You acknowledge and agree that the Telegram bot operates exclusively based on the parameters you set and does not make any decisions based on your input. MEMEPUMP will not be responsible for any losses, damages, or legal liabilities arising from your use of the Telegram bot. You are fully responsible for any profits or losses arising from your transactions.</p>
            <p className="mt-2">You are responsible for all aspects of your trading activities. You can stop using the Telegram bot at any time and withdraw your Digital Assets at your discretion. The Telegram bot will stop operating immediately or within a reasonable time frame, depending on the type of bot you are using. You acknowledge that any pending transactions may need to be completed or canceled before stopping the service completely.</p>
            <p className="mt-2">When you receive instructions to do so, the Telegram bot will stop operating immediately or within a reasonable time frame, depending on the type of bot you are using. You acknowledge that any pending transactions may need to be completed or canceled before stopping the service completely.</p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">4. FEES</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">4.1 Service Fees</h3>
            <p>By conducting transactions through our Services, you agree to pay any applicable fees as listed in our fee schedule, available on our Website. We may automatically deduct these fees from your Wallet for each transaction.</p>
            <p className="mt-2">We reserve the right to change or modify our fee schedule at any time. Any changes will take effect when posted on our Website or our Application. Using our Services for the first time after any fee changes will constitute your acceptance of those changes. If you do not agree with the updated fees, you may stop using our Services as set forth in this Agreement.</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">4.2 Additional Fees</h3>
            <p>Please note that in addition to our service fees, various other fees may apply to your transactions, including gas fees, slippage, platform fees, and other fees charged by network validators, third-party service providers, and other parties outside MEMEPUMP. To be clear, MEMEPUMP only charges service fees for the Services we provide.</p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">5. REGISTRATION</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">5.1 Representation</h3>
            <p>You represent that you are not subject to any restrictions on your use of the Services under the laws of your jurisdiction or any other jurisdiction. You are responsible for all activities that occur under your account.</p>
            <p className="mt-2">You agree that you will monitor your use of the Services to prevent unauthorized use by minors, and you will accept full responsibility for any unauthorized use of the Services by minors.</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">5.2 Additional Representation</h3>
            <p>You represent that you are at least 18 years old and that you understand the Services before engaging in any transactions through MEMEPUMP. Additionally, you represent that you are not located in, under the control of, or a citizen or resident of Afghanistan, Cuba, Iran, North Korea, or Syria ("Prohibited Jurisdictions").</p>
            <p className="mt-2">Additionally, you are not on the economic sanctions list of the United Nations, the United States Office of Foreign Assets Control, or the European Union. You will not provide any Digital Assets you have purchased or stored or any Services to Prohibited Jurisdictions, citizens or residents of Prohibited Jurisdictions, or any prohibited person.</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">5.3 Necessary Devices and Software</h3>
            <p>You must prepare all necessary devices, software, and hardware to connect to the Services. You are fully responsible for any fees incurred, including Internet or mobile data fees, arising from accessing the Services.</p>
            <p className="mt-2">You are fully responsible for securing your own hardware and software. MEMEPUMP will not be responsible if someone else accesses your device and initiates a transaction on your behalf. MEMEPUMP will not be responsible for any unauthorized transactions initiated by someone else on your behalf.</p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">6. RESPONSIBILITY FOR CONTENT</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">6.1 Types of Content</h3>
            <p>You acknowledge that all Content, including the Services, is the sole responsibility of the party from which it originates. This means that you and other Registered Users of the Services, not MEMEPUMP, are responsible for all Content provided by you and other Registered Users.</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">6.2 Adapter</h3>
            <p>You are fully responsible for any Adapter you provide on or through the Services, including but not limited to ensuring that any rights or licenses you have do not infringe on MEMEPUMP's rights or those of its licensors. You acknowledge and agree that MEMEPUMP does not have an obligation to publish or provide you with any Adapter on or through the Services. You acknowledge and agree that you do not have any rights to any upgrades, modifications, improvements, or changes that MEMEPUMP may make to your Adapter. You agree that we do not have an obligation to provide any support or technical assistance regarding your Adapter except upon our mutual agreement in writing.</p>
            <p className="mt-2">You acknowledge and agree that MEMEPUMP does not have an obligation to publish or provide you with any Adapter on or through the Services. You acknowledge and agree that you do not have any rights to any upgrades, modifications, improvements, or changes that MEMEPUMP may make to your Adapter. You agree that we do not have an obligation to provide any support or technical assistance regarding your Adapter except upon our mutual agreement in writing.</p>
            <p className="mt-2">You agree that we do not have an obligation to provide any support or technical assistance regarding your Adapter except upon our mutual agreement in writing.</p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">7. OWNERSHIP</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">7.1 Services</h3>
            <p>Except for any OSS, your Wallet and any User Content you provide, you agree that MEMEPUMP and its licensors own all rights, ownership, and interests in and to the Services. You will not delete, modify, or obscure any copyright, trademark, service mark, or other proprietary notices, logos, or marks that are included in or associated with the Services.</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">7.2 Open Source Software</h3>
            <p>You acknowledge that the Services may use, combine, or link with certain OSS and your use of the Services must comply with, and you will comply with any applicable open source license. Each OSS is provided under the terms of the applicable open source license accompanying it. There is nothing in this Agreement that limits your rights under, or grants you rights beyond, any applicable open source license. If requested by any open source license, MEMEPUMP will provide the OSS and any modifications MEMEPUMP makes to it in response to your request in writing at the contact information provided below.</p>
            <p className="mt-2">There is nothing in this Agreement that limits your rights under, or grants you rights beyond, any applicable open source license. If requested by any open source license, MEMEPUMP will provide the OSS and any modifications MEMEPUMP makes to it in response to your request in writing at the contact information provided below.</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">7.3 Trademarks</h3>
            <p>MEMEPUMP, and all graphics, logos, service marks, and trade names associated with the Services are trademarks of MEMEPUMP and may not be used without permission in connection with any Services or in connection with any products or services that are not ours. Other trademarks, service marks, and trade names may appear on or in connection with the Services but are the property of their respective owners.</p>
            <p className="mt-2">MEMEPUMP, and all graphics, logos, service marks, and trade names associated with the Services are trademarks of MEMEPUMP and may not be used without permission in connection with any Services or in connection with any products or services that are not ours. Other trademarks, service marks, and trade names may appear on or in connection with the Services but are the property of their respective owners.</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">7.4 User Content</h3>
            <p>MEMEPUMP does not claim ownership of User Content. However, when you use the Services as a Registered User and post or publish User Content (including but not limited to any Adapter), you represent that you own and/or have, and you grant MEMEPUMP, and its affiliates, successors, assigns, and licensees, a non-exclusive, worldwide, perpetual, irrevocable, non-cancelable, royalty-free, fully paid-up license to use, copy, distribute, publicly perform, publicly display, modify, create derivative works, and otherwise exploit User Content in any and all media now known or hereafter developed, for the full term of any rights you have in User Content. You also represent that you have the necessary rights to grant this license to MEMEPUMP. If you provide any Adapter in connection with any Brand, you represent and warrant that you have all the necessary rights in and to that Brand to grant MEMEPUMP the licenses set forth herein.</p>
            <p className="mt-2">If you provide any Adapter in connection with any Brand, you represent and warrant that you have all the necessary rights in and to that Brand to grant MEMEPUMP the licenses set forth herein.</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">7.5 Feedback</h3>
            <p>You agree that submitting Feedback is at your own risk and that MEMEPUMP will not be liable for any Feedback you submit. You represent and warrant that you have all the necessary rights to submit Feedback.</p>
            <p className="mt-2">You hereby grant MEMEPUMP, and its affiliates, successors, assigns, and licensees, a non-exclusive, worldwide, perpetual, irrevocable, non-cancelable, royalty-free, fully paid-up license to use, copy, distribute, publicly perform, publicly display, modify, create derivative works, and otherwise exploit Feedback in any and all media now known or hereafter developed, for the full term of any rights you have in Feedback. You also represent that you have the necessary rights to grant this license to MEMEPUMP. If you submit any Feedback in connection with any Brand, you represent and warrant that you have all the necessary rights to submit Feedback in connection with that Brand.</p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">8. USER BEHAVIOR RESTRICTIONS</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">8.1 Legal Liability</h3>
            <p>You agree that you are fully responsible for your conduct in connection with the Services. You agree that you will comply with this Agreement and will not (and will not attempt to):</p>
          </div>
          <ul className="list-decimal list-inside space-y-1 ml-4 text-sm">
            <li>8.2 Providing false or misleading information to MEMEPUMP;</li>
            <li>8.3 Using or attempting to use another Registered User's Wallet without that Registered User's permission;</li>
            <li>8.4 Impersonating any person or entity;</li>
            <li>8.5 Using the Services in any manner that could interfere with, disrupt, negatively affect, or inhibit other Registered Users from fully enjoying the Services, or that could damage, disable, overburden, or impair the functioning of the Services in any way;</li>
            <li>8.6 Developing, using, or distributing any software, or interacting with any API in any way, that could damage, harm, or impair the Services;</li>
            <li>8.7 Bypassing or circumventing measures used to prevent or restrict access to any service, area, or code of the Services;</li>
            <li>8.8 Attempting to circumvent any content filtering techniques we employ;</li>
            <li>8.9 Using any robot, spider, crawler, scraper, script, browser extension, offline reader, or other automated means or interface not authorized by us to access the Services, extract data, or interfere with or modify the rendering of Service pages or functionality;</li>
            <li>8.10 Collecting or harvesting data from our Services to contact individuals, companies, or other persons or entities, or using any such data to contact such entities;</li>
            <li>8.11 Using data collected from our Services for any direct marketing activity (including but not limited to email marketing, SMS marketing, telemarketing, and direct marketing);</li>
            <li>8.12 Bypassing or ignoring instructions that control all automated access to the Services;</li>
            <li>8.13 Using the Services for any unlawful or unauthorized purpose, or engaging in, encouraging, or promoting any activity that violates any applicable law or this Agreement;</li>
            <li>8.14 Using your Wallet to conduct any unlawful activity in connection with or in any way related to your access to and use of the Services, including but not limited to money laundering, terrorist financing, or knowingly engaging in activities designed to adversely affect the performance of the Services;</li>
            <li>8.15 Engaging in or knowingly facilitating any front-running, wash trading, pump and dump trading, ramping, cornering, or other fraudulent, deceptive, or manipulative trading activities;</li>
            <li>8.16 Using the Services to conduct any financial activity that requires registration or licensing, including but not limited to using the Services to trade securities, debt financing, equity financing, or other similar transactions;</li>
            <li>8.17 Using the Services to engage in fundraising for a business, protocol, or platform, including but not limited to creating, listing, or purchasing assets (i) that are redeemable for a financial instrument, (ii) that entitle holders to participate in an ICO or any securities offering, or (iii) that enable holders to receive financial rewards, including but not limited to DeFi yield rewards, staking rewards, and burn discounts;</li>
            <li>8.18 Providing any Content that infringes any patent, trademark, trade secret, copyright, right of publicity, or other right of any person or entity;</li>
            <li>8.19 Attempting to access any Wallet that you do not have legal authority to access.</li>
          </ul>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">9. INVESTIGATION</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">9.1 Right to Investigate and Monitor</h3>
            <p>MEMEPUMP may, but is not obligated to, monitor or review the Services and Content at any time. Without limiting the foregoing, MEMEPUMP reserves the right, at its sole discretion, to remove any Content for any reason (or no reason), including if such Content violates the Agreement or any applicable law.</p>
            <p className="mt-2">Although MEMEPUMP does not regularly monitor user activity in connection with the Services or Content, if MEMEPUMP becomes aware of any possible violations by you of any provision of the Agreement, MEMEPUMP reserves the right to investigate such violations, and MEMEPUMP may, at its sole discretion, immediately terminate your license to use the Services, or alter, modify, or remove your User Content, in whole or in part, without prior notice to you.</p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">10. INTERACTIONS WITH OTHER USERS</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">10.1 User Responsibility</h3>
            <p>You are solely responsible for your interactions with other Registered Users and any other parties with whom you interact; however, MEMEPUMP reserves the right, but has no obligation, to intervene in such disputes. You agree that MEMEPUMP will not be liable for any liability arising from such interactions.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">10.2 Responsibility for Connected Content</h3>
            <p>MEMEPUMP is not liable to you in connection with your use of MEMEPUMP's Services or any third party's viewing of Connected Content you have made public. MEMEPUMP DISCLAIMS ALL LIABILITY FOR CONNECTED CONTENT, INCLUDING BUT NOT LIMITED TO PERSONALLY IDENTIFIABLE INFORMATION, THAT MAY BE PROVIDED TO IT BY SUCH THIRD-PARTY SERVICE PROVIDERS IN VIOLATION OF THE PRIVACY SETTINGS YOU HAVE ESTABLISHED.</p>
            <p className="mt-2">MEMEPUMP does not attempt to review any Connected Content for any purpose, including but not limited to accuracy, legality, or non-infringement, and MEMEPUMP is not responsible for any Connected Content.</p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">11. INDEMNIFICATION</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">11.1 Indemnification Obligation</h3>
            <p>You agree to indemnify and hold harmless the MEMEPUMP Parties from any losses, costs, liabilities, and expenses (including reasonable attorneys' fees) relating to or arising from any and all of the following: (a) your User Content; (b) your use of, or inability to use, any of the Services; (c) your violation of the Agreement; (d) your violation of any rights of another party, including any Registered User; or (e) your violation of any applicable laws, rules, or regulations.</p>
            <p className="mt-2">MEMEPUMP reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will cooperate fully with MEMEPUMP in asserting any available defenses.</p>
            <p className="mt-2">This provision does not require you to indemnify any MEMEPUMP Party for any unreasonable business practices or for fraud, deception, false promises, misrepresentation, or concealment, suppression, or omission of any material fact in connection with the Website or any Services provided hereunder.</p>
            <p className="mt-2">You agree that the terms in this section will survive any termination of the Agreement and/or your access to the Services.</p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">12. ACCEPTANCE OF RISKS RELATED TO BLOCKCHAIN TECHNOLOGY</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">12.1 Transaction and Blockchain Risks</h3>
            <p>To be successfully completed, any transaction involving Digital Assets initiated by or sent to your Wallet must be confirmed by and recorded on the blockchain supporting such Digital Asset. MEMEPUMP has no control over any blockchain and therefore cannot and does not ensure that any transaction details you submit or receive through our Services will be validated by or confirmed on the relevant blockchain and is unable to facilitate any cancellation or modification requests.</p>
            <p className="mt-2">Additionally, some Ecosystem Partners may support complex financial transactions that carry a high degree of risk. You accept and acknowledge that you are solely responsible for all activities you undertake through your Wallet and accept all risks of loss, including loss due to any authorized or unauthorized access to your Wallet, to the maximum extent permitted by law.</p>
            <p className="mt-2">You further accept and acknowledge that: (a) you have the necessary technical expertise and ability to review and evaluate the security, integrity, and operation of your Wallet; (b) you have the knowledge, experience, understanding, professional advice, and information to make your own evaluation of the value, risks, and requirements for compliance under applicable laws for any use of your Wallet; (c) you know, understand, and accept the risks associated with your Wallet; and (d) you accept the risks associated with blockchain technology generally, and are responsible for conducting your own independent analysis of the specific risks of any Digital Assets you purchase or sell. You further agree that MEMEPUMP will not be responsible or liable for such risks.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">12.2 Price Volatility</h3>
            <p>The price of Digital Assets can be extremely volatile. MEMEPUMP makes no guarantees regarding the markets in which Digital Assets are transferred, purchased, or traded.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">12.3 Tax Responsibility</h3>
            <p>You are solely responsible for determining any taxes that may apply to your Digital Asset transactions. MEMEPUMP is not responsible for determining the taxes that apply to your Digital Asset transactions.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">12.4 Storage and Transfer of Digital Assets</h3>
            <p>MEMEPUMP does not store, send, or receive Digital Assets. This is because Digital Assets exist only by virtue of the ownership record maintained on the supporting blockchain, and therefore any transfer of Digital Assets occurs within the supporting blockchain and not within the Services.</p>
            <p className="mt-2">Transaction details you submit through the Services may not be completed, or may be substantially delayed, due to activity or inactivity on the blockchain used to process the transaction. Once transaction details have been submitted through your Wallet, MEMEPUMP cannot assist you to cancel or otherwise modify your transaction or transaction details.</p>
            <p className="mt-2">MEMEPUMP makes no warranties or guarantees that a transfer initiated on the Services will transfer title or right in any Digital Asset. There are risks associated with using Internet-based currency, including but not limited to, the risk of hardware, software, and Internet connections; the risk of introduction of malicious software; the risk that third parties may obtain unauthorized access to information stored within your Wallet; and the risk of counterfeit, mislabeled, or vulnerable assets, assets on faulty smart contracts, and assets that may become non-transferable.</p>
            <p className="mt-2">You accept and acknowledge that MEMEPUMP will not be responsible for any communication failures, disruptions, errors, distortions, or delays or losses you may experience when using blockchain technology, however caused.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">12.5 Legal and Policy Risks</h3>
            <p>The regulatory regime governing blockchain technology, cryptocurrencies, and tokens is uncertain, and new regulations or policies may adversely affect the development of the Services and the utility of Digital Assets.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">12.6 Decentralized Governance and Protocol Changes</h3>
            <p>MEMEPUMP makes no guarantees regarding the decentralized governance of any blockchain, which may, among other things, result in delays, conflicts of interest, or operational decisions unfavorable to some holders of certain Digital Assets.</p>
            <p className="mt-2">You acknowledge and accept that the protocols governing the operation of the blockchain may be subject to sudden changes in operating rules that may significantly alter the blockchain and affect the value and function of Digital Assets supported by that blockchain.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">12.7 Blockchain Security</h3>
            <p>MEMEPUMP makes no guarantees regarding the security of any blockchain. MEMEPUMP is not responsible for any hacks, double-spending, stolen Digital Assets, or any other attacks on the blockchain.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">12.8 Reliance on Third-Party Wallets and Ecosystem Partners</h3>
            <p>The Services rely on, and MEMEPUMP does not guarantee or warrant the functionality or access to, any third-party Wallets (such as MetaMask and Ledger) and Ecosystem Partners to perform any transactions. MEMEPUMP makes no guarantees regarding the decentralized governance of any blockchain, which may, among other things, result in delays, conflicts of interest, or operational decisions unfavorable to some holders of certain Digital Assets. You acknowledge and accept that the protocols governing the operation of the blockchain may be subject to sudden changes in operating rules that may significantly alter the blockchain and affect the value and function of Digital Assets supported by that blockchain.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">12.9 Repeated Security Risks</h3>
            <p>MEMEPUMP makes no guarantees regarding the security of any blockchain. MEMEPUMP is not responsible for any hacks, double-spending, stolen Digital Assets, or any other attacks on the blockchain.</p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">13. DISCLAIMER OF WARRANTIES AND CONDITIONS</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">13.1 As Is</h3>
            <p><span className="font-bold">YOU UNDERSTAND AND AGREE THAT TO THE EXTENT PERMITTED BY APPLICABLE LAW, YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK, AND THE SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITH ALL FAULTS.</span> The MEMEPUMP Parties expressly disclaim all warranties, representations, and conditions of any kind, whether express or implied, including, but not limited to, the implied warranties or conditions of merchantability, fitness for a particular purpose, and non-infringement arising from use of the Website.</p>
            <p className="mt-2">The MEMEPUMP Parties make no warranty, representation, or condition that: (1) the Services will meet your requirements; (2) your use of the Services will be uninterrupted, timely, secure, or error-free; or (3) the results that may be obtained from the use of the Services will be accurate or reliable. Any content downloaded from or accessed through the Services is accessed at your own risk, and you will be solely responsible for any damage to your property, including but not limited to your computer system and any device you use to access the Services, or any other loss that results from accessing such content.</p>
            <p className="mt-2">The Services may be subject to delays, cancellations, and other disruptions. MEMEPUMP makes no warranty, representation, or condition with respect to the Services, including but not limited to quality, effectiveness, reputation, and other characteristics of the Services. No advice or information, whether oral or written, obtained from MEMEPUMP or through the Services will create any warranty not expressly stated herein.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">13.2 No Responsibility for Third-Party Conduct</h3>
            <p>You acknowledge and agree that the MEMEPUMP Parties are not liable, and you agree not to seek to hold the MEMEPUMP Parties liable, for the conduct of third parties, including operators of external websites, and that the risk of injury from such third parties rests entirely with you.</p>
            <p className="mt-2">MEMEPUMP makes no warranty that goods or services provided by third parties will meet your requirements or be available on an uninterrupted, secure, or error-free basis. MEMEPUMP makes no warranty as to the quality of any goods or services, or the accuracy, timeliness, truthfulness, completeness, or reliability of any Connected Content obtained through the Services.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">13.3 Investigation and Damages Disclaimer</h3>
            <p>Notwithstanding anything to the contrary in these Terms of Service, MEMEPUMP will have no obligation to investigate and will not be responsible for any damages, other liability, or harm to any person or entity relating to (i) the ownership, validity, or authenticity of any Digital Asset; (ii) the collectability, insurability, effectiveness, marketability, or suitability of any Digital Asset; or (iii) any loss, delay, failure, error, interruption, or loss of data occurring directly or indirectly due to circumstances beyond MEMEPUMP's control, including but not limited to the failure of the blockchain, third-party service providers, or Ecosystem Partners.</p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">14. LIMITATION OF LIABILITY</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">14.1 Disclaimer of Certain Damages</h3>
            <p>You understand and agree that, to the extent permitted by law, in no event will the MEMEPUMP Parties be liable for any loss of profits, Ethereum or other virtual currency, revenue or data, indirect, incidental, special, or consequential damages, or damages or costs due to loss of production or use, business interruption, or procurement of substitute goods or services, in each case whether or not MEMEPUMP has been advised of the possibility of such damages, arising out of or in connection with the Agreement or any communication, interaction, or meeting with other users of the Services, on any theory of liability, resulting from: (a) the use or inability to use the Services; (b) the cost of procurement of substitute goods or services resulting from any goods, data, information, or services purchased or obtained; or messages received for transactions made through the Services; (c) unauthorized access to or alteration of your data or transmissions; (d) statements or conduct of any third party on the Services; or (e) any other matter related to the Services, whether based on warranty, copyright, contract, tort (including negligence), product liability, or any other legal theory.</p>
            <p className="mt-2">The above limitation of liability will not apply to the liability of a MEMEPUMP Party for (i) death or personal injury caused by a MEMEPUMP Party's negligence; or (ii) any injury caused by fraud or fraudulent misrepresentation of a MEMEPUMP Party.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">14.2 Limitation of Liability</h3>
            <p>To the extent permitted by law, the MEMEPUMP Parties will not be liable to you for more than the greater of (a) $1000; or (b) the remedy or penalty imposed by the statute under which such claim arises.</p>
            <p className="mt-2">The above limitation of liability will not apply to the liability of a MEMEPUMP Party for (i) death or personal injury caused by a MEMEPUMP Party's negligence; or (ii) any injury caused by fraud or fraudulent misrepresentation of a MEMEPUMP Party.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">14.3 Exclusion of Damages</h3>
            <p>Some jurisdictions do not allow the exclusion or limitation of certain damages. If these laws apply to you, some or all of the above exclusions or limitations may not apply to you, and you may have additional rights.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">14.4 Basis of the Agreement</h3>
            <p>The limitations of damages set forth above are fundamental elements of the basis of the agreement between MEMEPUMP and you.</p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">15. TERM AND TERMINATION</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">15.1 Term</h3>
            <p>The Agreement commences on the date you accept it (as described in the preamble above) and will remain in full force and effect while you use the Services, unless earlier terminated in accordance with the Agreement.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">15.2 Termination of Services by MEMEPUMP</h3>
            <p>MEMEPUMP reserves the right to terminate (or suspend access to) your use of the Services for any reason at our sole discretion, including your violation of this Agreement. MEMEPUMP has the sole discretion to determine whether you have violated any restrictions set forth in this Agreement.</p>
            <p className="mt-2">If we suspend your use of the Services, you may continue to access your Wallet directly or through other services not hosted by us. MEMEPUMP will not be liable to you for any suspension or termination.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">15.3 Termination of Services by You</h3>
            <p>If you wish to terminate the Services provided by MEMEPUMP, you may do so by discontinuing use of the Services. You may continue to access your Wallet directly or through other services not hosted by us.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">15.4 Survival</h3>
            <p>All provisions of the Agreement which by their nature should survive, will survive termination of the Services, including but not limited to, provisions regarding ownership, warranty disclaimers, and limitations of liability.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">15.5 No Further Use</h3>
            <p>If your access to the Services or any other MEMEPUMP community is terminated by MEMEPUMP, you agree that you will not attempt to access the Services or any MEMEPUMP community through use of another Wallet, Third-Party Account, member name, or otherwise.</p>
            <p className="mt-2">In the event you violate the immediately preceding sentence, MEMEPUMP reserves the right, at its sole discretion, to immediately take any or all actions set forth herein without notice or warning to you.</p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">16. GOVERNING LAW AND DISPUTE RESOLUTION</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">16.1 Waiver of Class or Non-Individual Arbitration</h3>
            <p>ALL DISPUTES, CLAIMS, AND REQUESTS FOR RELIEF WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE RESOLVED BY ARBITRATION ON AN INDIVIDUAL BASIS AND NOT ON A CLASS OR COLLECTIVE BASIS, ONLY INDIVIDUAL RELIEF IS AVAILABLE, AND CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER.</p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">17. THIRD-PARTY SERVICES</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">17.1 Third-Party Services</h3>
            <p>The Services may contain or, in some cases, integrate with our Services, certain Third-Party Services. When you click on a link to or access or use a Third-Party Service, we will not warn you that you have left the Services and are subject to the terms and conditions (including privacy policies) of another website or destination.</p>
            <p className="mt-2">Such Third-Party Services are not under the control of MEMEPUMP. MEMEPUMP is not responsible for any Third-Party Services. MEMEPUMP provides these Third-Party Services only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Services, or any products or services offered in connection with them. You use all links in Third-Party Services at your own risk.</p>
            <p className="mt-2">When you leave our Services, this Agreement and our policies no longer govern. You should review the applicable terms and policies, including data collection and security practices, of any Third-Party Service, and make whatever investigation you feel necessary or appropriate before proceeding with any transaction with any third party.</p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">18. REFERRAL PROGRAM</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">18.1 Sharing Referral Links</h3>
            <p>Sharing Referral Links.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">18.2 Reservation of Rights</h3>
            <p>MEMEPUMP may suspend or terminate the Referral Program or your ability to participate in this program at any time for any reason. For example, we reserve the right to review and investigate all referral activities, and suspend access to the Services or revoke or disable any earned Incentives at our sole discretion if we determine any activity that we believe is abusive, fraudulent, in violation of this Agreement or any Additional Referral Terms, or otherwise unfair and inappropriate.</p>
            <p className="mt-2">We also reserve the right to disable Referral Links or change the Incentives related to the use of any Referral Link or Referral Program offer at any time for any reason. Without limiting the foregoing, MEMEPUMP reserves the right, at its sole discretion, to revoke or disable any Incentive that it determines, in its sole discretion, was obtained (i) in violation of this Agreement, including but not limited to, (1) not meeting eligibility requirements and (2) through distribution via unauthorized channels or in violation of any applicable law, rule, or regulation; or (ii) in connection with content that MEMEPUMP deems offensive or inappropriate in its sole discretion.</p>
            <p className="mt-2">Without limiting the foregoing, such content includes all forms of pornography, obscenity, language and content that incites or promotes hostility or violence, denigrates, defames, or harms the goodwill, reputation, or brand image of MEMEPUMP, or incites or promotes discrimination of any kind.</p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-xl font-bold mb-3">19. GENERAL PROVISIONS</h2>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold mb-2">19.1 Electronic Communications</h3>
            <p>For contractual purposes, you (a) consent to receive communications from MEMEPUMP in electronic form; and (b) agree that all terms and conditions, agreements, notices, disclosures, and other communications that MEMEPUMP provides to you electronically satisfy any legal requirement that such communications would satisfy if they were in writing.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">19.2 Release</h3>
            <p>You hereby release the MEMEPUMP Parties and their successors from claims, demands, any and all losses, damages, rights, and actions of any kind, including personal injury, death, and property damage, either directly or indirectly related to or arising from your use of the Services, including but not limited to, any interactions with or conduct of other Registered Users or third-party websites of any kind arising in connection with or as a result of the Agreement or your use of the Services.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">19.3 Assignment</h3>
            <p>The Agreement, and your rights and obligations hereunder, may not be assigned, delegated, or transferred by you without the prior written consent of MEMEPUMP, and any attempted assignment, delegation, or transfer in violation of the foregoing will be null and void.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">19.4 Force Majeure</h3>
            <p>MEMEPUMP will not be liable for any delay or failure to perform resulting from causes outside its reasonable control, including, but not limited to, acts of God, war, terrorism, riots, embargoes, acts of civil or military authorities, fire, floods, accidents, strikes, or shortages of transportation, fuel, energy, labor, or materials.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">19.5 Questions, Complaints, Requests</h3>
            <p>If you have any questions, complaints, or requests regarding the Services, please contact us at <a href="https://t.me/MemePumpOfficial" className="text-blue-600 underline" target="_blank" rel="noopener noreferrer">https://t.me/MemePumpOfficial</a> or <a href="https://x.com/MemePump7" className="text-blue-600 underline" target="_blank" rel="noopener noreferrer">https://x.com/MemePump7</a>.</p>
            <p className="mt-2">We will do our best to address your concerns. If you feel that your concerns have not been fully addressed, we invite you to let us know for further investigation.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">19.6 Waiver</h3>
            <p>Any waiver or failure to enforce any provision of the Agreement in one instance will not be deemed a waiver of any other provision or of such provision in any other instance.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">19.7 Severability</h3>
            <p>If any part of this Agreement is held to be invalid or unenforceable, that part will be construed in a manner to reflect, as nearly as possible, the original intent of the parties, and the remaining portions will remain in full force and effect.</p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">19.8 Entire Agreement</h3>
            <p>The Agreement is the final, complete, and exclusive agreement of the parties with respect to the subject matter hereof and supersedes and merges all prior discussions between the parties with respect to such subject matter.</p>
          </div>
        </div>
      </div>
    </div>
  )
}
